---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-selfsigned-ca
  namespace: glueops-core-vault
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"

spec:
  isCA: true
  commonName: Vault CA
  secretName: vault-ca-secret
  duration: 87660h0m0s # 10 years
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-certificate
  namespace: glueops-core-vault
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: vault-tls
  duration: 9528h0m0s
  renewBefore: 1080h0m0s
  dnsNames:
  - '*.glueops-core-vault.svc.cluster.local'
  - '*.vault-internal'
  - '*.vault-internal.glueops-core-vault.svc.cluster.local'
  - '*.glueops-core-vault'
  ipAddresses:
  - '127.0.0.1'
  issuerRef:
    name: vault-ca-issuer
  commonName: vault cert
