---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-ca-issuer
  namespace: glueops-core-vault
  annotation:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ca:
    secretName: vault-ca-secret